### DISCUSSION TITLE
special  selectors

### DISCUSSION THREAD

**Discussion by ph4un00b** [stylify/packages#152] [Q&A] [answered]
Hello, congrats on the awesome idea! I support yielding the minimal for the user as well.  
I have a blocker in my way, what is the simplest approach to get selectors like this to work the stylify way?

```css
     <!--- nth-of-type(even) --->
     article:nth-of-type(even) {
        display: flex;
        flex-flow: column;
        flex-direction: row-reverse;
      }
      
      <!--- ~ * --->
      details[open] summary ~ * {
        animation: open 0.3s ease-in-out;
      }

     <!--- ::-webkit-details-marker --->
      details summary::-webkit-details-marker {
        display: none;
      }
```
